### ISSUE TITLE
Design experience around T&C agreement

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/hca-ebi-user-value#5]
Design the user flow for agreeing to the T&C.
Needs a review of the current mocks

User story:
Additional requirements:

Need review from implementation perspective: dev team
Needs review from wrangler perspective: wrangler team

Acceptance criteria:

- Mocks are created which can be used by the current dev team for functional interactions.
- Implementation allows to record a user's name and email address for T&Cs.
- Wranglers and UX have reviewed/tested this.
- Users, and wranglers are notified.

Dependant on:
Help from webdev frontend team with visuals and branding.

**Comment by justincc** [comment]
Is this system use t&c, project t&c or both?
